# Generated by Django 2.2 on 2020-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'SportsWear'), ('OW', 'OutWear')], default='S', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('d', 'danger'), ('p', 'primary'), ('s', 'secondary')], default='p', max_length=1),
        ),
    ]
