# Generated by Django 2.2 on 2020-03-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='email',
            field=models.EmailField(default='john@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='message',
            field=models.TextField(default='Message'),
            preserve_default=False,
        ),
    ]
